[config]
schemaVersion = "0.0.1"

[package]
namespace = "TeamXiaolan"
name = "DawnLib"
description = "A modern API for Lethal Company content and all sizes of mods"
websiteUrl = "https://github.com/TeamXiaolan/DawnLib"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2304"
Hamunii-AutoHookGenPatcher = "1.0.9"
Evaisa-FixPluginTypesSerialization = "1.1.4"
Zaggy1024-PathfindingLib = "2.4.0"
mattymatty-MonkeyInjectionLibrary = "1.0.1"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "../Packages"

[[build.copy]]
source = "../DawnLib/bin/Release/netstandard2.1/com.github.teamxiaolan.dawnlib.dll"
target = "BepInEx/plugins/DawnLib/"

[[build.copy]]
source = "../DawnLib.Dusk/bin/Release/netstandard2.1/com.github.teamxiaolan.dawnlib.dusk.dll"
target = "BepInEx/plugins/DawnLib/"

[[build.copy]]
source = "../DawnLib.Compatibility/bin/Release/netstandard2.1/com.github.teamxiaolan.dawnlib.compatibility.dll"
target = "BepInEx/plugins/DawnLib/"

[[build.copy]]
source = "../DawnLib.Interfaces/bin/Release/netstandard2.1/com.github.teamxiaolan.dawnlib.interfaces.dll"
target = "BepInEx/plugins/DawnLib/"

[[build.copy]]
source = "../DawnLib/data"
target = "BepInEx/plugins/DawnLib/data/"

[[build.copy]]
source = "../DawnLib/res/dawnlibmain"
target = "BepInEx/plugins/DawnLib/Assets/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "mods", "tools", "libraries", "clientside", "serverside" ]