name: Publish

on:
  release:
    types: [released]

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      ref: ${{ github.event.release.tag_name }}

  upload-release-artifacts:
    name: Upload Release Artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v6

      - name: Download all artifacts
        uses: actions/download-artifact@v7

      - name: Upload artifacts to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} thunderstore-build/*.zip nupkg-build/*/bin/Release/*.nupkg

  deploy-thunderstore:
    name: Deploy to Thunderstore
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v6

      - name: Download Thunderstore artifact
        uses: actions/download-artifact@v7
        with:
          name: thunderstore-build

      - name: Setup .NET SDK
        uses: ./.github/actions/setup-dotnet

      - name: Restore dotnet tools
        run: |
          dotnet tool restore

      - name: Publish to Thunderstore
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.THUNDERSTORE_TOKEN }}
        run: |
          dotnet build -target:PublishThunderstore

  deploy-nuget:
    name: Deploy to NuGet
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Download nupkg artifact
        uses: actions/download-artifact@v7
        with:
          name: nupkg-build

      - name: Setup .NET SDK
        uses: ./.github/actions/setup-dotnet

      - name: Publish to NuGet.org
        run: |
          dotnet nuget push ./*/bin/Release/*.nupkg --api-key ${{ secrets.DAWNLIB_NUGET }} --source https://api.nuget.org/v3/index.json
